- hosts: localhost
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-instance

- hosts: mastodonHarvester
  gather_facts: true
  roles:
    - role: common
    - role: install-docker
