---
- name: finish cluster setup
  ansible.builtin.shell:
    cmd: "curl -XPOST \"http://{{ username }}:{{ password }}@{{ masternode }}:5984/_cluster_setup\"
      --header \"Content-Type: application/json\" 
      --data '{\"action\": \"finish_cluster\"}'"

