swagger: "2.0"

info:
  title: Charity data related
  description: Charity related data from tweets, mastodon, and sudo data
  version: "0.1"

paths:
  /healthcheck:
    get:
        operationId: app.flask.routes.healthcheck
        summary: OK.
        responses:
          200:
            description: Successful response.
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: healthcheck message.
  /data/sudo/home_and_community_care:
    get:
        operationId: app.flask.routes.data_home_and_community_care
        summary: Return list of sudo data for home and community care
        produces:
          - application/json
        responses:
          200:
            description: SUDO data retrieved successfully
            schema:
              $ref: '#/definitions/HomeAndCommunityCareResponse'
  /data/sudo/voluntary_work:
    get:
        operationId: app.flask.routes.data_voluntary_work
        summary: Return list of sudo data for volutary work
        produces:
          - application/json
        responses:
          200:
            description: SUDO data retrieved successfully
            schema:
              $ref: '#/definitions/VoluntaryWorkResponse'
  /data/sudo/unpaid_assistance:
    get:
        operationId: app.flask.routes.data_unpaid_assistance
        summary: Return list of sudo data for unpaid assistance
        produces:
          - application/json
        responses:
          200:
            description: SUDO data retrieved successfully
            schema:
              $ref: '#/definitions/UnpaidAssistanceResponse'
  /data/twitter/related:
    get:
        operationId: app.flask.routes.data_twitter_related_tweets
        summary: Return aggregated count of tweets grouped by states
        produces:
          - application/json
        responses:
          200:
            description: Twitter view data retrieved successfully
            schema:
              $ref: '#/definitions/KeyStrValItem'
  /data/twitter/unrelated:
    get:
        operationId: app.flask.routes.data_twitter_unrelated_tweets
        summary: Return aggregated count of related and unrelated tweets
        produces:
          - application/json
        responses:
          200:
            description: Twitter view data retrieved successfully
            schema:
              $ref: '#/definitions/KeyStrValItem'
  /data/mastodon/toots:
    get:
        operationId: app.flask.routes.data_mastodon_toots
        summary: Return aggregated count of tweets grouped by states
        produces:
          - application/json
        responses:
          200:
            description: Twitter view data retrieved successfully
            schema:
              $ref: '#/definitions/KeyValItem'
  /data/mastodon/users:
    get:
        operationId: app.flask.routes.data_mastodon_users
        summary: Return aggregated count of realted and unrelated tweets
        produces:
          - application/json
        responses:
          200:
            description: Twitter view data retrieved successfully
            schema:
              $ref: '#/definitions/KeyValItem'
definitions:
  HomeAndCommunityCareResponse:
    type: array
    items:
      type: object
      properties:
        hcc_cco_1_no_7_12_6_13:
          type: number
        hcc_dom_1_no_7_12_6_13:
          type: number
        area_code:
          type: integer
        area_name:
          type: string
        hcc_day_1_no_7_12_6_13:
          type: number
        hcc_toti_1_no_7_12_6_13:
          type: number
        hcc_mls_1_no_7_12_6_13:
          type: number
        hcc_cns_1_no_7_12_6_13:
          type: number
  VoluntaryWorkResponse:
    type: array
    items:
      type: object
      properties:
        P_Tot_Volunteer:
          type: integer
          format: int32
        P_Tot_N_a_volunteer:
          type: integer
          format: int32
        P_Tot_Voluntary_work_ns:
          type: integer
          format: int32
        P_85ov_Volunteer:
          type: integer
          format: int32
        SA2_MAIN11:
          type: string
  UnpaidAssistanceResponse:
    type: array
    items:
      type: object
      properties:
        f_tot_no_upaid_assist_pvded:
          type: integer
        lga_code_2016:
          type: string
  KeyStrValItem:
    type: array
    items:
      type: object
      properties:
        key:
          type: string
        value:
          type: integer
  KeyValItem:
    type: array
    items:
      type: object
      properties:
        key:
          type: integer
        value:
          type: integer