swagger: "2.0"

info:
  title: Swagger Template
  description: A Template API
  version: "0.1"

paths:
  /healthcheck:
    get:
        operationId: app.flask.routes.healthcheck
        summary: Returns a greeting.
        responses:
          200:
            description: Successful response.
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: Message greeting.