- hosts: localhost
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-instance

- hosts: COMP90024
  gather_facts: true

  roles:
    - role: common
    - role: docker
