- hosts: localhost
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    # - role: openstack-security-group
    - role: openstack-volume
    - role: openstack-instance-master
    - role: openstack-instance-clusters

# install docker on both master and other cluster nodes
- hosts: CouchDBMaster
  gather_facts: true
  roles:
    - role: common
    - role: install-docker

- hosts: CouchDBClusters
  gather_facts: true
  roles:
    - role: common
    - role: install-docker

# mount volumes to both master and other cluster nodes
- hosts: CouchDBMaster
  gather_facts: true
  vars_files:
    - host_vars/couchdb.yaml
  roles:
    - role: volumes
    - role: couchdb

# also start cluster settings
- hosts: CouchDBClusters
  gather_facts: true
  vars_files:
    - host_vars/couchdb.yaml
  roles:
    - role: volumes
    - role: couchdb
    - role: couchdb-cluster

# finish cluster settings
- hosts: CouchDBMaster
  gather_facts: true
  vars_files:
    - host_vars/couchdb.yaml
  roles:
    - role: couchdb-cluster-finish